resolver: lts-7.24
# Sadly, Elm 0.18 doesn't support GHC 8
packages:
- .
- location:
    git: https://github.com/tmhedberg/here.git
    commit: 8a616b358bcc16bd215a78a8f6192ad9df8224b6
  extra-dep: true


extra-deps:
  - http-types-0.8.6
  - aeson-pretty-0.7.2
  - containers-0.5.10.2
  - binary-0.7.6.1
  - optparse-applicative-0.13.2.0

flags: {}

nix:
  enable: true
  pure: false
  shell-file: shell.nix

skip-ghc-check: true
